global:
 scrape_interval: 1s
 scrape_timeout: 1s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets: ['localhost:9090']
remote_write:
 - url: http://<INFLUX-CONTAINER-NAME>:8086/api/v1/prom/write?db=<PROMETHEUS_DB_NAME>
